language: bash

sudo: required

services:
  - docker

env:
  global:
    - MSGPACK_VERSION=2.0.3
    - IGBINARY_VERSION=3.0.1
    - MEMCACHED_VERSION=3.1.3
    - REDIS_VERSION=4.3.0
    - IMAGICK_VERSION=3.4.3
    - APCU_VERSION=5.1.7
    - MONGO_VERSION=1.5.3
    - YAML_VERSION=2.0.4
  matrix:
##     5.6
##    - VERSION=5.6 VARIANT=cli PHP_VERSION=5.6.40
##    - VERSION=5.6 VARIANT=fpm-base PHP_VERSION=5.6.40
##    7.0
#    - VERSION=7.0 VARIANT=cli PHP_VERSION=7.0.33
#    - VERSION=7.0 VARIANT=fpm-base PHP_VERSION=7.0.33
##    7.1
    - VERSION=7.1 VARIANT=cli PHP_VERSION=7.1.28
    - VERSION=7.1 VARIANT=fpm-base PHP_VERSION=7.1.28
##    7.2
    - VERSION=7.2 VARIANT=cli PHP_VERSION=7.2.17
    - VERSION=7.2 VARIANT=fpm-base PHP_VERSION=7.2.17
##    7.3
    - VERSION=7.3 VARIANT=cli PHP_VERSION=7.3.4
    - VERSION=7.3 VARIANT=fpm-base PHP_VERSION=7.3.4

before_install:
  - export DOCKER_COMPOSE_VERSION=1.24.0
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image="larvacent/php:${VERSION}-${VARIANT}"

script:
  - travis_retry docker build --build-arg PHP_VERSION=${PHP_VERSION} --build-arg MSGPACK_VERSION=${MSGPACK_VERSION} --build-arg IGBINARY_VERSION=${IGBINARY_VERSION} --build-arg MEMCACHED_VERSION=${MEMCACHED_VERSION} --build-arg REDIS_VERSION=${REDIS_VERSION} --build-arg IMAGICK_VERSION=${IMAGICK_VERSION} --build-arg APCU_VERSION=${APCU_VERSION} --build-arg MONGO_VERSION=${MONGO_VERSION} --build-arg YAML_VERSION=${YAML_VERSION} -t "$image" .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login --username="${DOCKER_REGISTRY_USER}" --password="${DOCKER_REGISTRY_PASSWORD}";
      docker push $image;
      docker tag $image larvacent/php:${PHP_VERSION}-${VARIANT};
      docker push larvacent/php:${PHP_VERSION}-${VARIANT};
      if [ "${VERSION}" == "7.2" ]; then
        if [ "${VARIANT}" == "fpm" ]; then
          docker tag $image larvacent/php:latest;
          docker push larvacent/php:latest;
          docker tag $image larvacent/php:${PHP_VERSION};
          docker push larvacent/php:${PHP_VERSION};
          docker tag $image larvacent/php:${VERSION};
          docker push larvacent/php:${VERSION};
        fi
      fi
    fi

# vim:set et ts=2 sw=2:
